/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.app.logintrack.model;

import com.app.logintrack.service.persistence.LoginDataPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LoginData service. Represents a row in the &quot;LR_APP_LoginData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.app.logintrack.model.impl.LoginDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.app.logintrack.model.impl.LoginDataImpl}.
 * </p>
 *
 * @author Pankaj Kathiriya
 * @see LoginData
 * @see com.app.logintrack.model.impl.LoginDataImpl
 * @see com.app.logintrack.model.impl.LoginDataModelImpl
 * @generated
 */
public interface LoginDataModel extends BaseModel<LoginData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a login data model instance should use the {@link LoginData} interface instead.
	 */

	/**
	 * Returns the primary key of this login data.
	 *
	 * @return the primary key of this login data
	 */
	public LoginDataPK getPrimaryKey();

	/**
	 * Sets the primary key of this login data.
	 *
	 * @param primaryKey the primary key of this login data
	 */
	public void setPrimaryKey(LoginDataPK primaryKey);

	/**
	 * Returns the user ID of this login data.
	 *
	 * @return the user ID of this login data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this login data.
	 *
	 * @param userId the user ID of this login data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this login data.
	 *
	 * @return the user uuid of this login data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this login data.
	 *
	 * @param userUuid the user uuid of this login data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the login date of this login data.
	 *
	 * @return the login date of this login data
	 */
	public Date getLoginDate();

	/**
	 * Sets the login date of this login data.
	 *
	 * @param loginDate the login date of this login data
	 */
	public void setLoginDate(Date loginDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoginData loginData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoginData> toCacheModel();

	@Override
	public LoginData toEscapedModel();

	@Override
	public LoginData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}