/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.app.logintrack.model.impl;

import com.app.logintrack.model.LoginData;
import com.app.logintrack.model.LoginDataModel;
import com.app.logintrack.service.persistence.LoginDataPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LoginData service. Represents a row in the &quot;LR_APP_LoginData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.app.logintrack.model.LoginDataModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoginDataImpl}.
 * </p>
 *
 * @author Pankaj Kathiriya
 * @see LoginDataImpl
 * @see com.app.logintrack.model.LoginData
 * @see com.app.logintrack.model.LoginDataModel
 * @generated
 */
public class LoginDataModelImpl extends BaseModelImpl<LoginData>
	implements LoginDataModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a login data model instance should use the {@link com.app.logintrack.model.LoginData} interface instead.
	 */
	public static final String TABLE_NAME = "LR_APP_LoginData";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", Types.BIGINT },
			{ "loginDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table LR_APP_LoginData (userId LONG not null,loginDate DATE not null,primary key (userId, loginDate))";
	public static final String TABLE_SQL_DROP = "drop table LR_APP_LoginData";
	public static final String ORDER_BY_JPQL = " ORDER BY loginData.id.userId ASC, loginData.id.loginDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LR_APP_LoginData.userId ASC, LR_APP_LoginData.loginDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.app.logintrack.model.LoginData"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.app.logintrack.model.LoginData"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.app.logintrack.model.LoginData"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long LOGINDATE_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.app.logintrack.model.LoginData"));

	public LoginDataModelImpl() {
	}

	@Override
	public LoginDataPK getPrimaryKey() {
		return new LoginDataPK(_userId, _loginDate);
	}

	@Override
	public void setPrimaryKey(LoginDataPK primaryKey) {
		setUserId(primaryKey.userId);
		setLoginDate(primaryKey.loginDate);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new LoginDataPK(_userId, _loginDate);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((LoginDataPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return LoginData.class;
	}

	@Override
	public String getModelClassName() {
		return LoginData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userId", getUserId());
		attributes.put("loginDate", getLoginDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date loginDate = (Date)attributes.get("loginDate");

		if (loginDate != null) {
			setLoginDate(loginDate);
		}
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public Date getLoginDate() {
		return _loginDate;
	}

	@Override
	public void setLoginDate(Date loginDate) {
		_loginDate = loginDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public LoginData toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoginData)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoginDataImpl loginDataImpl = new LoginDataImpl();

		loginDataImpl.setUserId(getUserId());
		loginDataImpl.setLoginDate(getLoginDate());

		loginDataImpl.resetOriginalValues();

		return loginDataImpl;
	}

	@Override
	public int compareTo(LoginData loginData) {
		LoginDataPK primaryKey = loginData.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoginData)) {
			return false;
		}

		LoginData loginData = (LoginData)obj;

		LoginDataPK primaryKey = loginData.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		LoginDataModelImpl loginDataModelImpl = this;

		loginDataModelImpl._originalUserId = loginDataModelImpl._userId;

		loginDataModelImpl._setOriginalUserId = false;

		loginDataModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LoginData> toCacheModel() {
		LoginDataCacheModel loginDataCacheModel = new LoginDataCacheModel();

		loginDataCacheModel.userId = getUserId();

		Date loginDate = getLoginDate();

		if (loginDate != null) {
			loginDataCacheModel.loginDate = loginDate.getTime();
		}
		else {
			loginDataCacheModel.loginDate = Long.MIN_VALUE;
		}

		return loginDataCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", loginDate=");
		sb.append(getLoginDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.app.logintrack.model.LoginData");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loginDate</column-name><column-value><![CDATA[");
		sb.append(getLoginDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LoginData.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LoginData.class
		};
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _loginDate;
	private long _columnBitmask;
	private LoginData _escapedModel;
}